apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-beta-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-beta-frontend
  template:
    metadata:
      labels:
        app: tenant-beta-frontend
    spec:
      containers:
      - name: frontend
        image: himeshp/react-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
