apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-beta-app
  namespace: argocd
spec:
  project: tenant-beta
  source:
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    targetRevision: HEAD
    path: argocd-tenants/workloads/tenant-beta
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
